### ISSUE TITLE
How to test with electron-builder ? 

### ISSUE THREAD

**Issue by andirsun** [spaceagetv/electron-playwright-example#6]
I want to use this example and helpers with electron-buider.

**Comment by jjeff** [comment]
I have not used electron-builder before, but this project actually runs the Playwright tests against the packaged Electron application (in the "out" directory), so the tests should still work with an electron-builder workflow.

If you want to fork this project and create an electron-builder version, I will happily link to it and/or include instructions in this project.

**Comment by Ruslan-AER** [comment]
you have a few options i didn't run full tests on this but in the helpers you need to change a line,
from 
`const outDir = path.join(rootDir,'out');`
to
`const outDir = path.join(rootDir, 'release', 'build');`

don't forget to build the app before starting the test.

second option that i'm using is, install the app then 
`electronApp = await electron.launch({
      executablePath: 'C:\path\To\app.exe,
    });`
i'm only developing for windows i don't know about other platforms.
